### PR TITLE
Upgrade to Rust 1.24.0

### LINKED ISSUE #120: document minimum required rust version in BUILD.md
Error information:

```bash
error[E0599]: no method named `eq_ignore_ascii_case` found for type `&str` in the current scope
  --> proxy/src/fully_qualified_authority.rs:56:19
   |
56 |             (part.eq_ignore_ascii_case("svc"), false)
   |                   ^^^^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use std::ascii::AsciiExt;`

error: aborting due to previous error

error: Could not compile `conduit-proxy`.
```

I run this build in ubuntu 16.04 with rustc 1.22.1. Should I upgrade to rustc 1.23 to build conduit?

### LINKED ISSUE #362: Uprade to Rust 1.24.0
The new phone book is here! https://blog.rust-lang.org/2018/02/15/Rust-1.24.html

### PR DESCRIPTION
**Pull request by olix0r**
Rust 1.24.0, the newest stable version of the rust compiler, was released
today.

This changes the default version used for docker builds.

Additionally, I have added a sentence to the rust section of BUILD.md
noting that we only support the most recent stable version of Rust.

Fixes #120 
Fixes #362

### CODE REVIEW

**Comment by briansmith** [comment]
> Note that Rust 1.24 makes link-time-optimization less aggressive by default so you should run the proxy performance tests to verify there are no performance regressions.

It also changes the default of codegen-units in a way that might have negative performance implications, as called out in the release notes.

**Comment by olix0r** [comment]
```sh
for v in 1.24.0 1.23.0 ; do
  time docker build . -f proxy/Dockerfile --build-arg=RUST_IMAGE=rust:$v --no-cache
done
```


* `rust:1.24.0`  `1.44s user 0.91s system 0% cpu 13:52.11 total`
* `rust:1.23.0`   `1.41s user 1.02s system 0% cpu 13:59.41 total`

**Comment by briansmith** [comment]
Just to be clear, when I said we should look for performance regressions, I meant runtime performance regressions (the performance of the proxy itself), not build performance regressions. The new default compilation strategy results in less inlining and less inter-module optimization in order to get faster builds.
