### ISSUE TITLE
document minimum required rust version in BUILD.md

### ISSUE THREAD

**Issue by skyao** [runconduit/conduit#120]
Error information:

```bash
error[E0599]: no method named `eq_ignore_ascii_case` found for type `&str` in the current scope
  --> proxy/src/fully_qualified_authority.rs:56:19
   |
56 |             (part.eq_ignore_ascii_case("svc"), false)
   |                   ^^^^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use std::ascii::AsciiExt;`

error: aborting due to previous error

error: Could not compile `conduit-proxy`.
```

I run this build in ubuntu 16.04 with rustc 1.22.1. Should I upgrade to rustc 1.23 to build conduit?

**Comment by hawkw** [comment]
@skyao that's correct, `rustc` 1.23 is required to build Conduit.

**Comment by briansmith** [comment]
The bug here is that we don't document the minimum required version of Rust in https://github.com/runconduit/conduit/blob/master/BUILD.md.
